### ISSUE TITLE
Docker pwpush-postgres missing assets

### ISSUE THREAD

**Issue by XSlicer** [pglombardo/PasswordPusher#163]
For some reason the pwpush-postgres is giving 404's on all assets since tag 1.4 (1.5 has the same issues). 1.2 and 1.3 work fine.
This is with a fresh download with docker-compose.yaml

The following error is logged in production.log inside the docker:

```
F, [2020-12-01T15:23:38.177804 #18] FATAL -- : [f75e7933-a4a5-4394-b598-086864e64b44]   
F, [2020-12-01T15:23:38.177864 #18] FATAL -- : [f75e7933-a4a5-4394-b598-086864e64b44] ActionController::RoutingError (No route matches [GET] "/assets/application-992cb2c46eaf7dc549d5bb1a8efa00537726d681d2d47e57d05dc4c765d18cc7.js"):
F, [2020-12-01T15:23:38.177884 #18] FATAL -- : [f75e7933-a4a5-4394-b598-086864e64b44]   
F, [2020-12-01T15:23:38.177927 #18] FATAL -- : [f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:38:in `call_app'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:151:in `block in call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-timeout-0.6.0/lib/rack/timeout/support/timeout.rb:19:in `timeout'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:150:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `public_send'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `method_missing'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/chunked.rb:98:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/unicorn-5.6.0/lib/unicorn/http_server.rb:632:in `process_client'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/unicorn-5.6.0/lib/unicorn/http_server.rb:728:in `worker_loop'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/unicorn-5.6.0/lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/unicorn-5.6.0/lib/unicorn/http_server.rb:144:in `start'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/gems/unicorn-5.6.0/bin/unicorn:128:in `<top (required)>'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/bin/unicorn:23:in `load'
[f75e7933-a4a5-4394-b598-086864e64b44] vendor/bundle/ruby/2.7.0/bin/unicorn:23:in `<main>'
```
```
# docker logs -f docker_passwordpusher_1
15:23:38 web.1         | 172.21.0.1 - - [01/Dec/2020:15:23:38 +0000] "GET /assets/application-992cb2c46eaf7dc549d5bb1a8efa00537726d681d2d47e57d05dc4c765d18cc7.js HTTP/1.1" 403 - 0.0012
15:23:38 web.1         | 172.21.0.1 - - [01/Dec/2020:15:23:38 +0000] "GET /404 HTTP/1.1" 404 728 0.0016
```

I don't really have a lot of Ruby knowledge so I wasn't able to debug this sadly.

**Comment by pglombardo** [comment]
Thanks for reporting @XSlicer - let me take a look and I'll post back here soon.

**Comment by ohermosa** [comment]
@pglombardo i get the same 404 errors few time after deploy the container with docker-compose

```yaml
  secrets:
    image: pglombardo/pwpush-postgres
    container_name: secrets
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://${SECRETS_USER}:${SECRETS_PASS}@postgres:5432/${SECRETS_DB}"
    expose:
      - "5000"
    depends_on:
      - postgres
```

@XSlicer did you "lose" the css with these errors?

![image](https://user-images.githubusercontent.com/8667345/107791380-2b88d400-6d54-11eb-978d-2660339f8176.png)

Thanks and best regards

**Comment by pglombardo** [comment]
Apologies for the delayed fix but this is now fixed in `pwpush-postgres:latest` (aka 1.6):
https://hub.docker.com/repository/registry-1.docker.io/pglombardo/pwpush-postgres/tags?page=1&ordering=last_updated

Could one or both of you try that latest version out and let me know if assets are now being properly served?

**Comment by neg2led** [comment]
@pglombardo as it happens, I've just deployed a pwpush-postgres:latest deployment and the assets are being served just fine:

![image](https://user-images.githubusercontent.com/4232981/107892908-260dd280-6f7c-11eb-9954-ac613cd1a12e.png)

Can't confirm for others, of course, but looks like I timed my deployment well! 😄

**Comment by pglombardo** [comment]
Yay that's great.  Thanks for letting me know.

**Comment by XSlicer** [comment]
Yes, this version indeed seems to have solves the issue. Thanks for fixing it!
