### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by riahc3** [pglombardo/PasswordPusher#2157]
## 🐛 Bug Report

I open the page and while the PasswordPusher favicon appears, I get a Rate Limit Exceeded

## 🔬 How To Reproduce

Im using a PasswordPusher instance using Docker connecting to a MariaDB

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [X] Docker Image
  - [X] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

### Screenshots

![image](https://github.com/pglombardo/PasswordPusher/assets/1131521/37fd375c-2db8-4ebb-a45a-468cb7009f50)

## 📈 Expected behavior

The regular Password Pusher page to show up

**Comment by pglombardo** [comment]
Your configured health checks might be too aggressive.  You can configure the throttling (rate limiting) in your `settings.yml`: https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#throttling

**Comment by riahc3** [comment]
> Your configured health checks might be too aggressive. You can configure the throttling (rate limiting) in your `settings.yml`: https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#throttling

I believe I left them by default.

![image](https://github.com/pglombardo/PasswordPusher/assets/1131521/a18ff2ea-3371-4993-b682-865dc2f9e769)


I dont have any issues uppering the limits. 

I could set it to 2147483648 correct?

**Comment by riahc3** [comment]
Or, if I comment it out; Is it unlimited?

**Comment by riahc3** [comment]
Closed; Removing the limits works

**Comment by 0x25** [comment]
hello,

comment throttling (minute or second) raise an issue in rake component and docker not start

```rake aborted!
ArgumentError: Must pass :limit option (ArgumentError)

          raise ArgumentError, "Must pass #{opt.inspect} option" unless options[opt]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/rack-attack-6.7.0/lib/rack/attack/throttle.rb:14:in `block in initialize'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/rack-attack-6.7.0/lib/rack/attack/throttle.rb:13:in `each'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/rack-attack-6.7.0/lib/rack/attack/throttle.rb:13:in `initialize'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/rack-attack-6.7.0/lib/rack/attack/configuration.rb:72:in `new'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/rack-attack-6.7.0/lib/rack/attack/configuration.rb:72:in `throttle'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/forwardable-1.3.3/lib/forwardable.rb:240:in `throttle'
/opt/PasswordPusher/config/initializers/rack_attack.rb:34:in `<class:Attack>'
/opt/PasswordPusher/config/initializers/rack_attack.rb:2:in `<main>'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/engine.rb:689:in `load'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/engine.rb:689:in `block in load_config_initializer'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1.2/lib/active_support/notifications.rb:212:in `instrument'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/engine.rb:688:in `load_config_initializer'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/engine.rb:642:in `block (2 levels) in <class:Engine>'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/engine.rb:641:in `each'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/engine.rb:641:in `block in <class:Engine>'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/initializable.rb:32:in `instance_exec'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/initializable.rb:32:in `run'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/initializable.rb:50:in `each'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/initializable.rb:60:in `run_initializers'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/application.rb:435:in `initialize!'
/opt/PasswordPusher/config/environment.rb:7:in `<main>'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/application.rb:411:in `require_environment!'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1.2/lib/rails/application.rb:559:in `block in run_tasks_blocks'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:58:in `load'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:23:in `run'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/cli.rb:455:in `exec'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/cli.rb:35:in `dispatch'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/cli.rb:29:in `start'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/exe/bundle:28:in `block in <top (required)>'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.17/exe/bundle:20:in `<top (required)>'
```

**Comment by pglombardo** [comment]
Hi @0x25 - I created #2684 and will take a look soon.  Thanks for reporting!
