### ISSUE TITLE
'NameError: uninitialized constant Lockbox' when building v1.10.4 or master

### ISSUE THREAD

**Issue by jeffdesc** [pglombardo/PasswordPusher#264]
Hey

When building the MySQL version (from the `pwpush-mysql` directory) I am receiving a Lockbox error:

```
#14 4.016 NameError: uninitialized constant Lockbox
```

The full build log:
```
[+] Building 193.6s (14/14) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 35B                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ruby:3.0.2                                                                                                                   0.6s
 => CACHED [ 1/11] FROM docker.io/library/ruby:3.0.2@sha256:179ae4287b6bb0b9f03d09cd1f10c2aba7e34c60183c838b2ea00bcdd85c43d7                                                    0.0s
 => [ 2/11] RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -                                                                                               0.9s
 => [ 3/11] RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list                                                                   0.3s
 => [ 4/11] RUN apt-get update -qq &&     apt-get install -qq -y --assume-yes build-essential apt-utils git curl tzdata zlib1g-dev nodejs yarn &&     cd /opt &&     git clon  12.9s
 => [ 5/11] RUN gem install bundler                                                                                                                                             1.3s
 => [ 6/11] WORKDIR /opt/PasswordPusher                                                                                                                                         0.0s
 => [ 7/11] RUN bundle config set without 'development private test'                                                                                                            0.5s
 => [ 8/11] RUN bundle config set deployment 'true'                                                                                                                             0.5s
 => [ 9/11] RUN bundle install                                                                                                                                                127.1s
 => [10/11] RUN yarn install                                                                                                                                                   45.1s
 => ERROR [11/11] RUN bundle exec rails webpacker:compile                                                                                                                       4.1s
------
 > [11/11] RUN bundle exec rails webpacker:compile:
#14 4.013 rails aborted!
**#14 4.016 NameError: uninitialized constant Lockbox**
#14 4.016 /opt/PasswordPusher/config/initializers/lockbox.rb:26:in `<main>'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:205:in `instrument'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/engine.rb:680:in `load_config_initializer'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/engine.rb:633:in `each'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `instance_exec'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `run'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:50:in `each'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:60:in `run_initializers'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/application.rb:391:in `initialize!'
#14 4.016 /opt/PasswordPusher/config/environment.rb:82:in `<main>'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/application.rb:367:in `require_environment!'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/application.rb:533:in `block in run_tasks_blocks'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:20:in `execute'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:50:in `invoke'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
#14 4.016 /opt/PasswordPusher/gemfiles/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
#14 4.017 Tasks: TOP => webpacker:compile => environment
#14 4.017 (See full trace by running task with --trace)
------
executor failed running [/bin/sh -c bundle exec rails webpacker:compile]: exit code: 1
```

I've tried this from the tag v1.10.4 or master, both resulting in this error.
What can be done to resolve this error?

Kind regards
Jeffrey

**Comment by pglombardo** [comment]
Hrm [our Github Action](https://github.com/pglombardo/PasswordPusher/runs/4129348687?check_suite_focus=true) also failed with this recent change.  It seems to only happen on the mysql container.  I'll take a look and post back soon.

**Comment by pglombardo** [comment]
Apologies for the issue - it should be resolved now with the latest commit on master branch.

**Comment by jeffdesc** [comment]
Hey Peter

No need for apologies. Thank you very much for the quick fix.

Can this be backported to the latest tag/release (v1.10.4) so we can use a fixed tag or can a new release be created? We'd love to use this tool, but not on the master branch of course.

**Comment by pglombardo** [comment]
Backporting is troublesome.  I can tag a new release but this will also include the new encryption scheme that was merged before this fix.  The change is transparent for users, but you may want to set a custom encryption key ahead of time.

I posted some details here:
https://twitter.com/pwpush/status/1456674952317476881

I'll tag `v1.11.0` soon.

**Comment by jeffdesc** [comment]
Alright thanks for the information. Any ETA on `v1.11.0`? I'll wait for the new tag until we start releasing this internally.

**Comment by pglombardo** [comment]
Ok I just pushed the tag now.  The containers are building: https://github.com/pglombardo/PasswordPusher/actions/runs/1435275892

They usually take 30 mins.  I'll check back on them in a bit.

**Comment by jeffdesc** [comment]
Awesome Peter! Thanks for the quick support, I can proceed now.
Have a nice day.
