### ISSUE TITLE
SMTP Config Error

### ISSUE THREAD

**Issue by karkazzul** [pglombardo/PasswordPusher#373]
Hello,

I am using docker-compose for pwpush. I have settup pwpush with postgres backend. The connexion is ok with postgres.

But, the mail config doesn't work. 
Here you can see the env variables for the smtp:
```yaml
      - PWP__ENABLE_LOGINS=true
      - PWP__ALLOW_ANONYMOUS=false
      - PWP__MAIL__RAISE_DELIVERY_ERRORS=false
      - PWP__MAIL__SMTP_ADDRESS=smtp.google.com
      - PWP__MAIL__SMTP_PORT=587
      - PWP__MAIL__SMTP_USER_NAME=email.google@google.com
      - PWP__MAIL__SMTP_PASSWORD=password
      #- PWP__MAIL__SMTP_AUTHENTICATION=plain
      - PWP__MAIL__SMTP_STARTTLS=true
      - PWP__MAIL__OPEN_TIMEOUT=10
      - PWP__MAIL__READ_TIMEOUT=10
      - PWP__HOST_DOMAIN=pwpush.domain.com
      - PWP__HOST_PROTOCOL=https
      - PWP__MAIL__MAILER_SENDER='"company" <email.google@google.com>'
```

Here the production file:
```log
E, [2022-08-04T11:51:57.583979 #11] ERROR -- : source=rack-timeout id=3748eea0-0f5c-4d2c-96b1-15c8e40edce0 timeout=15000ms service=15000ms state=timed_out
F, [2022-08-04T11:51:57.587694 #11] FATAL -- : [3748eea0-0f5c-4d2c-96b1-15c8e40edce0]   
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ):
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0]   
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] /usr/local/lib/ruby/3.0.0/socket.rb:60:in `wait_writable'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] /usr/local/lib/ruby/3.0.0/socket.rb:60:in `connect_internal'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] /usr/local/lib/ruby/3.0.0/socket.rb:137:in `connect'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] /usr/local/lib/ruby/3.0.0/socket.rb:642:in `block in tcp'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] /usr/local/lib/ruby/3.0.0/socket.rb:227:in `each'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] /usr/local/lib/ruby/3.0.0/socket.rb:227:in `foreach'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] /usr/local/lib/ruby/3.0.0/socket.rb:632:in `tcp'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] net-smtp (0.3.1) lib/net/smtp.rb:626:in `tcp_socket'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] net-smtp (0.3.1) lib/net/smtp.rb:639:in `do_start'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] net-smtp (0.3.1) lib/net/smtp.rb:604:in `start'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] mail (2.7.1) lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] mail (2.7.1) lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] mail (2.7.1) lib/mail/message.rb:2159:in `do_delivery'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] mail (2.7.1) lib/mail/message.rb:260:in `block in deliver'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionmailer (6.1.6) lib/action_mailer/base.rb:559:in `block in deliver_mail'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `block in instrument'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `instrument'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionmailer (6.1.6) lib/action_mailer/base.rb:557:in `deliver_mail'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] mail (2.7.1) lib/mail/message.rb:260:in `deliver'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionmailer (6.1.6) lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionmailer (6.1.6) lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionmailer (6.1.6) lib/action_mailer/message_delivery.rb:118:in `deliver_now'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] devise (4.8.1) lib/devise/models/authenticatable.rb:204:in `send_devise_notification'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] devise (4.8.1) lib/devise/models/confirmable.rb:121:in `send_confirmation_instructions'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] devise (4.8.1) lib/devise/models/confirmable.rb:183:in `send_on_create_confirmation_instructions'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:427:in `block in make_lambda'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:260:in `block in conditional'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:516:in `block in invoke_after'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:516:in `each'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:516:in `invoke_after'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:107:in `run_callbacks'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:824:in `_run_commit_callbacks'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/transactions.rb:321:in `committed!'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:155:in `commit_records'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:304:in `block in commit_transaction'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:294:in `commit_transaction'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:351:in `block in within_new_transaction'[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/transactions.rb:298:in `save'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/suppressor.rb:44:in `save'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] devise (4.8.1) app/controllers/devise/registrations_controller.rb:19:in `create'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/abstract_controller/base.rb:228:in `process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] route_translator (12.1.0) lib/route_translator/extensions/action_controller.rb:18:in `set_locale_from_url'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actiontext (6.1.6) lib/action_text/rendering.rb:20:in `with_renderer'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actiontext (6.1.6) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:126:in `instance_exec'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:137:in `run_callbacks'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `block in instrument'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `instrument'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activerecord (6.1.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/abstract_controller/base.rb:165:in `process'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionview (6.1.6) lib/action_view/rendering.rb:39:in `process'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal.rb:190:in `dispatch'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_controller/metal.rb:254:in `dispatch'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/routing/mapper.rb:49:in `serve'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `each'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `serve'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-attack (6.6.1) lib/rack/attack.rb:127:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-throttle (0.7.0) lib/rack/throttle/limiter.rb:35:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-throttle (0.7.0) lib/rack/throttle/limiter.rb:35:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-throttle (0.7.0) lib/rack/throttle/limiter.rb:35:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-throttle (0.7.0) lib/rack/throttle/limiter.rb:35:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/etag.rb:27:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/conditional_get.rb:40:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/head.rb:12:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] sentry-rails (5.3.1) lib/sentry/rails/rescued_exception_interceptor.rb:9:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] sentry-ruby-core (5.3.1) lib/sentry/rack/capture_exceptions.rb:11:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] railties (6.1.6) lib/rails/rack/logger.rb:37:in `call_app'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] railties (6.1.6) lib/rails/rack/logger.rb:26:in `block in call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/tagged_logging.rb:37:in `tagged'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `tagged'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] railties (6.1.6) lib/rails/rack/logger.rb:26:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-timeout (0.6.3) lib/rack/timeout/core.rb:148:in `block in call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-timeout (0.6.3) lib/rack/timeout/support/timeout.rb:19:in `timeout'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-timeout (0.6.3) lib/rack/timeout/core.rb:147:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/method_override.rb:24:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/runtime.rb:22:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] activesupport (6.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/static.rb:24:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] actionpack (6.1.6) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] railties (6.1.6) lib/rails/engine.rb:539:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] railties (6.1.6) lib/rails/railtie.rb:207:in `public_send'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] railties (6.1.6) lib/rails/railtie.rb:207:in `method_missing'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] puma (5.6.4) lib/puma/configuration.rb:252:in `call'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] puma (5.6.4) lib/puma/server.rb:441:in `process_client'
[3748eea0-0f5c-4d2c-96b1-15c8e40edce0] puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```
And i'have this screen on the navigator when i attempt to registrer new users:
![image](https://user-images.githubusercontent.com/23294229/182842946-359ac8d3-34a2-4b9c-9534-12d86dcdbab0.png)

Thanks for tour help.

**Comment by pglombardo** [comment]
Hi @karkazzul - it can't connect because the smtp server address is wrong.  It should be `smtp.gmail.com`.

https://support.google.com/mail/answer/7104828?hl=en&visit_id=637953130786433476-2919880413&rd=1

**Comment by pglombardo** [comment]
If those are fake values you entered - then it is still an SMTP connect issue.  You could get a shell inside the container and run `nc -v smtp.gmail.com 587` to verify that the connection fails.

**Comment by karkazzul** [comment]
thanks for your help. it's working
