### ISSUE TITLE
More Secure pwpush-postgres example in README.md

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#412]
It is noted in https://github.com/pglombardo/PasswordPusher/tree/master/containers/docker#pwpush-postgres that:

> Note: Providing a PostgreSQL password on the command line is far less than ideal

The `docker.io/postgres:10` image supports the environmental variable `POSTGRES_PASSWORD_FILE` for defining a default root password.
The PostgreSQL provider being used by PasswordPusher supports the `passfile` parameter for the `postgresql` URI scheme to allow a user to provide a [Password File](https://www.postgresql.org/docs/10/libpq-pgpass.html).
One can provide password files to the Docker images by using the `--mount` or `-v` Docker parameter.

Example based on the original, let:
- `/var/opt/pwpush/server.db-secret` on the Docker host be the default root password for PostgreSQL
- `/var/opt/pwpush/client.db-secret` on the Docker host be the PostgreSQL Password File for PasswordPusher

```bash
docker network create pwpush-net
docker volume create pwpush-pgdata
docker run -d --name=pwpush-db -h postgres --restart=unless-stopped --network=pwpush-net -v pwpush-pgdata:/var/lib/postgresql/data -v /var/opt/pwpush/server.db-secret:/var/opt/pwpush/.db-secret:ro -e "POSTGRES_USER=pwpush" -e "POSTGRES_PASSWORD_FILE=/var/opt/pwpush/.db-secret" -e "POSTGRES_DB=pwpush" docker.io/postgres:10
docker run -d -p "5100:5100" --network=pwpush-net -v /var/opt/pwpush/client.db-secret:/var/opt/pwpush/.db-secret:ro -e "DATABASE_URL=postgresql://pwpush@postgres:5432/pwpush?passfile=/var/opt/pwpush/.db-secret" pglombardo/pwpush-postgres:latest
```

Additional guidance on how to secure the Password File(s) on the Docker host filesystem would need to also be provided.

**Comment by pglombardo** [comment]
Adding a new section to the documentation about postgres password files:
https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/README.md#better-security-with-password-files

Thanks for the report!

**Comment by hakunamatata97k** [comment]
@Viajaz @pglombardo In my case, I'm trying to take advantage of the already existing PostgreSQL docker container that is used by my Nextcloud container. 

First, I created a database ```pwpush``` and added access privileges to the existing user ```nextcloud```.
The compose section is 

```
  nextcloud-db:
    image: postgres:14
    container_name: nextcloud-db
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
  passwordpusher:
    image: pglombardo/pwpush-postgres:release
    container_name: passwordpusher
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "DATABASE_URL=postgresql://nextcloud@postgres:5432/pwpush?passfile=/run/secrets/postgres_password"
    ports:
      - 5100:5100
    depends_on:
      - nextcloud-db
    links:
      - nextcloud-db:postgres
    secrets:
      - postgres_password
```
this yielded the following errors: 
```
Attaching to passwordpusher
passwordpusher  | Password Pusher: migrating database to latest...
passwordpusher  | rake aborted!
passwordpusher  | ActiveRecord::ConnectionNotEstablished: fe_sendauth: no password supplied
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in new_client'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_handling.rb:280:in `connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
passwordpusher  | /usr/local/bundle/bin/bundle:25:in `load'
passwordpusher  | /usr/local/bundle/bin/bundle:25:in `<main>'
passwordpusher  |
passwordpusher  | Caused by:
passwordpusher  | PG::ConnectionBad: fe_sendauth: no password supplied
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/pg-1.4.5/lib/pg/connection.rb:632:in `async_connect_or_reset'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/pg-1.4.5/lib/pg/connection.rb:760:in `connect_to_hosts'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/pg-1.4.5/lib/pg/connection.rb:695:in `new'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/pg-1.4.5/lib/pg.rb:69:in `connect'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_handling.rb:280:in `connection'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
passwordpusher  | /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
passwordpusher  | /usr/local/bundle/bin/bundle:25:in `load'
passwordpusher  | /usr/local/bundle/bin/bundle:25:in `<main>'
passwordpusher  | Tasks: TOP => db:migrate
passwordpusher  | (See full trace by running task with --trace)
passwordpusher exited with code 1
```
What am I missing?

**Comment by pglombardo** [comment]
Hi @hakunamatata97k - I'm traveling this week - I'll take a look at this once I get back.

**Comment by pglombardo** [comment]
That `passfile` is not supported in the pwpush containers.  We've talked about adding support but nothing yet.  If you put the password directly into the `DATABASE_URL` environment variable it will work.

Others have mentioned Docker secrets but I haven't had the chance to try that out myself yet.
