### ISSUE TITLE
Heroku: Upgrade Ruby Version

### ISSUE THREAD

**Issue by bprobst-msis** [pglombardo/PasswordPusher#441]
Attempted a new deployment to Heroku and it failed when configuring Ruby.

> -----> Building on the Heroku-22 stack
> -----> Determining which buildpack to use for this app
>  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
> 			Detected buildpacks: Ruby,Node.js
> 			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
> -----> Ruby app detected
> -----> Installing bundler 2.3.10
> -----> Removing BUNDLED WITH version in the Gemfile.lock
> -----> Compiling Ruby/Rails
>        Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-22/ruby-3.0.4.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
>        Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-22/ruby-3.0.4.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
>  !
>  !     The Ruby version you are trying to install does not exist on this stack.
>  !     
>  !     You are trying to install ruby-3.0.4 on heroku-22.
>  !     
>  !     Ruby ruby-3.0.4 is present on the following stacks:
>  !     
>  !     - heroku-18
>  !     - heroku-20
>  !     
>  !     Heroku recommends you use the latest supported Ruby version listed here:
>  !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
>  !     
>  !     For more information on syntax for declaring a Ruby version see:
>  !     https://devcenter.heroku.com/articles/ruby-versions
>  !
>  !     Push rejected, failed to compile Ruby app.
>  !     Push failed

As per documentation linked in the error: 

> [Supported runtimes](https://devcenter.heroku.com/articles/ruby-support#supported-runtimes)
> Heroku supports the following Ruby versions and the associated Rubygems. A supported version means that you can expect our tools and platform to work with a given version. It also means you can receive technical support. Here are our supported Ruby versions:
> 
> MRI:
> 
> 2.7.6, Rubygems: 3.1.6 (Heroku-18 & Heroku-20 only)
> 3.0.4, Rubygems: 3.2.33(Heroku-18 & Heroku-20 only)
> 3.1.2, Rubygems: 3.3.7

I am unfortunately not proficient with Ruby at all, otherwise I would probably attempt to update the version requirement myself.

**Comment by pglombardo** [comment]
Hi @bprobst-msis - thanks for the report and apologies for the issue.  The heroku deploy file hasn't been updated in a while.  I'll see if I can resurrect it soon.

**Comment by pglombardo** [comment]
This may be a Heroku issue as the `app.json` file for these Heroku deploys hasn't changed in quite a while.  See linked issue above.

**Comment by bprobst-msis** [comment]
After specifying a specific stack to build with by adding ` "stack": "heroku-20",` to `app.json` and also when attempting to update my current instance I am getting the following build error: 
>        Running: rake assets:precompile
>        rake aborted!
>        LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.
> 
>        Caused by:
>        Gem::LoadError: pg is not part of the bundle. Add it to your Gemfile.

### Below is the output from creating a new instance in Heroku: 

> -----> Building on the Heroku-20 stack
> -----> Determining which buildpack to use for this app
> -----> Ruby app detected
> -----> Installing bundler 2.3.25
> -----> Removing BUNDLED WITH version in the Gemfile.lock
> -----> Compiling Ruby/Rails
> -----> Using Ruby version: ruby-3.0.4
> -----> Installing dependencies using bundler 2.3.25
>        Running: BUNDLE_WITHOUT='development:test:private' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
>        Fetching gem metadata from https://rubygems.org/.........
>        Fetching https://github.com/pglombardo/simple_token_authentication.git
>        Fetching rake 13.0.6
>        Installing rake 13.0.6
>        Fetching concurrent-ruby 1.2.0
>        Fetching minitest 5.17.0
>        Fetching builder 3.2.4
>        Fetching erubi 1.12.0
>        Installing erubi 1.12.0
>        Fetching racc 1.6.2
>        Installing minitest 5.17.0
>        Installing builder 3.2.4
>        Fetching crass 1.0.6
>        Fetching rack 2.2.6.2
>        Installing concurrent-ruby 1.2.0
>        Installing racc 1.6.2 with native extensions
>        Installing rack 2.2.6.2
>        Installing crass 1.0.6
>        Fetching nio4r 2.5.8
>        Fetching websocket-extensions 0.1.5
>        Installing nio4r 2.5.8 with native extensions
>        Fetching marcel 1.0.2
>        Installing websocket-extensions 0.1.5
>        Fetching mini_mime 1.1.2
>        Installing marcel 1.0.2
>        Fetching date 3.3.3
>        Installing date 3.3.3 with native extensions
>        Installing mini_mime 1.1.2
>        Fetching timeout 0.3.1
>        Installing timeout 0.3.1
>        Fetching jsonapi-renderer 0.2.2
>        Installing jsonapi-renderer 0.2.2
>        Fetching public_suffix 5.0.1
>        Installing public_suffix 5.0.1
>        Fetching execjs 2.8.1
>        Installing execjs 2.8.1
>        Fetching aws-eventstream 1.2.0
>        Installing aws-eventstream 1.2.0
>        Fetching aws-partitions 1.701.0
>        Installing aws-partitions 1.701.0
>        Fetching jmespath 1.6.2
>        Installing jmespath 1.6.2
>        Fetching faraday-em_http 1.0.0
>        Installing faraday-em_http 1.0.0
>        Fetching faraday-em_synchrony 1.0.0
>        Installing faraday-em_synchrony 1.0.0
>        Fetching faraday-excon 1.1.0
>        Installing faraday-excon 1.1.0
>        Fetching faraday-httpclient 1.0.1
>        Installing faraday-httpclient 1.0.1
>        Fetching multipart-post 2.3.0
>        Installing multipart-post 2.3.0
>        Fetching faraday-net_http 1.0.1
>        Installing faraday-net_http 1.0.1
>        Fetching faraday-net_http_persistent 1.2.0
>        Installing faraday-net_http_persistent 1.2.0
>        Fetching faraday-patron 1.0.0
>        Installing faraday-patron 1.0.0
>        Fetching faraday-rack 1.0.0
>        Installing faraday-rack 1.0.0
>        Fetching faraday-retry 1.0.3
>        Installing faraday-retry 1.0.3
>        Fetching ruby2_keywords 0.0.5
>        Installing ruby2_keywords 0.0.5
>        Fetching connection_pool 2.3.0
>        Installing connection_pool 2.3.0
>        Fetching bcrypt 3.1.18
>        Installing bcrypt 3.1.18 with native extensions
>        Fetching msgpack 1.6.0
>        Installing msgpack 1.6.0 with native extensions
>        Fetching popper_js 2.11.6
>        Installing popper_js 2.11.6
>        Fetching method_source 1.0.0
>        Installing method_source 1.0.0
>        Fetching thor 1.2.1
>        Installing thor 1.2.1
>        Fetching zeitwerk 2.6.6
>        Installing zeitwerk 2.6.6
>        Fetching ffi 1.15.5
>        Installing ffi 1.15.5 with native extensions
>        Fetching tilt 2.0.11
>        Installing tilt 2.0.11
>        Using bundler 2.3.25
>        Fetching deep_merge 1.2.2
>        Installing deep_merge 1.2.2
>        Fetching dry-initializer 3.1.1
>        Installing dry-initializer 3.1.1
>        Fetching dry-inflector 1.0.0
>        Installing dry-inflector 1.0.0
>        Fetching declarative 0.0.20
>        Installing declarative 0.0.20
>        Fetching orm_adapter 0.5.0
>        Installing orm_adapter 0.5.0
>        Fetching digest-crc 0.6.4
>        Installing digest-crc 0.6.4 with native extensions
>        Fetching foreman 0.87.2
>        Installing foreman 0.87.2
>        Fetching forwardable 1.3.3
>        Installing forwardable 1.3.3
>        Fetching locale 2.1.3
>        Installing locale 2.1.3
>        Using singleton 0.1.1
>        Fetching text 1.3.1
>        Installing text 1.3.1
>        Fetching jwt 2.6.0
>        Installing jwt 2.6.0
>        Fetching memoist 0.16.2
>        Installing memoist 0.16.2
>        Fetching multi_json 1.15.0
>        Installing multi_json 1.15.0
>        Fetching os 1.1.4
>        Installing os 1.1.4
>        Fetching httpclient 2.8.3
>        Installing httpclient 2.8.3
>        Fetching trailblazer-option 0.1.2
>        Installing trailblazer-option 0.1.2
>        Fetching uber 0.1.0
>        Installing uber 0.1.0
>        Fetching retriable 3.1.2
>        Installing retriable 3.1.2
>        Fetching rexml 3.2.5
>        Installing rexml 3.2.5
>        Fetching webrick 1.8.1
>        Installing webrick 1.8.1
>        Fetching google-cloud-errors 1.3.0
>        Installing google-cloud-errors 1.3.0
>        Fetching high_voltage 3.1.2
>        Installing high_voltage 3.1.2
>        Fetching json 2.6.3
>        Installing json 2.6.3 with native extensions
>        Fetching lockbox 1.1.1
>        Installing lockbox 1.1.1
>        Fetching oj 3.13.23
>        Installing oj 3.13.23 with native extensions
>        Fetching rack-timeout 0.6.3
>        Installing rack-timeout 0.6.3
>        Fetching rollbar 3.4.0
>        Installing rollbar 3.4.0
>        Fetching will_paginate 3.3.1
>        Installing will_paginate 3.3.1
>        Fetching i18n 1.12.0
>        Installing i18n 1.12.0
>        Fetching tzinfo 2.0.6
>        Installing tzinfo 2.0.6
>        Fetching rack-test 2.0.2
>        Installing rack-test 2.0.2
>        Fetching sprockets 4.2.0
>        Installing sprockets 4.2.0
>        Fetching warden 1.2.9
>        Installing warden 1.2.9
>        Fetching request_store 1.5.1
>        Installing request_store 1.5.1
>        Fetching rack-attack 6.6.1
>        Installing rack-attack 6.6.1
>        Fetching rack-cors 1.1.1
>        Installing rack-cors 1.1.1
>        Fetching websocket-driver 0.7.5
>        Installing websocket-driver 0.7.5 with native extensions
>        Fetching net-protocol 0.2.1
>        Installing net-protocol 0.2.1
>        Fetching addressable 2.8.1
>        Installing addressable 2.8.1
>        Fetching autoprefixer-rails 10.4.7.0
>        Installing autoprefixer-rails 10.4.7.0
>        Fetching terser 1.1.13
>        Installing terser 1.1.13
>        Fetching aws-sigv4 1.5.2
>        Installing aws-sigv4 1.5.2
>        Fetching faraday-multipart 1.0.4
>        Installing faraday-multipart 1.0.4
>        Fetching net-http-persistent 4.0.1
>        Installing net-http-persistent 4.0.1
>        Fetching nokogiri 1.14.0 (x86_64-linux)
>        Installing nokogiri 1.14.0 (x86_64-linux)
>        Fetching dry-core 1.0.0
>        Installing dry-core 1.0.0
>        Fetching puma 6.0.2
>        Fetching rack-throttle 0.7.0
>        Installing puma 6.0.2 with native extensions
>        Installing rack-throttle 0.7.0
>        Fetching bootsnap 1.16.0
>        Installing bootsnap 1.16.0 with native extensions
>        Using prime 0.1.2
>        Fetching representable 3.2.0
>        Installing representable 3.2.0
>        Fetching kramdown 2.4.0
>        Installing kramdown 2.4.0
>        Fetching will_paginate-bootstrap-style 0.2.4
>        Installing will_paginate-bootstrap-style 0.2.4
>        Fetching activesupport 7.0.4.2
>        Installing activesupport 7.0.4.2
>        Fetching net-imap 0.3.4
>        Installing net-imap 0.3.4
>        Fetching net-pop 0.1.2
>        Installing net-pop 0.1.2
>        Fetching net-smtp 0.3.3
>        Installing net-smtp 0.3.3
>        Fetching aws-sdk-core 3.170.0
>        Installing aws-sdk-core 3.170.0
>        Fetching faraday 1.10.3
>        Installing faraday 1.10.3
>        Fetching loofah 2.19.1
>        Installing loofah 2.19.1
>        Fetching dry-configurable 1.0.1
>        Installing dry-configurable 1.0.1
>        Fetching dry-logic 1.5.0
>        Installing dry-logic 1.5.0
>        Fetching sassc 2.4.0
>        Installing sassc 2.4.0 with native extensions
>        Fetching gettext 3.4.3
>        Installing gettext 3.4.3
>        Fetching rails-dom-testing 2.0.3
>        Installing rails-dom-testing 2.0.3
>        Fetching globalid 1.1.0
>        Installing globalid 1.1.0
>        Fetching activemodel 7.0.4.2
>        Installing activemodel 7.0.4.2
>        Fetching case_transform 0.2
>        Installing case_transform 0.2
>        Fetching mail 2.8.0.1
>        Installing mail 2.8.0.1
>        Fetching aws-sdk-kms 1.62.0
>        Installing aws-sdk-kms 1.62.0
>        Fetching faraday_middleware 1.2.0
>        Installing faraday_middleware 1.2.0
>        Fetching signet 0.17.0
>        Installing signet 0.17.0
>        Fetching google-cloud-env 1.6.0
>        Installing google-cloud-env 1.6.0
>        Fetching rails-html-sanitizer 1.5.0
>        Installing rails-html-sanitizer 1.5.0
>        Fetching dry-types 1.7.0
>        Installing dry-types 1.7.0
>        Fetching translation 1.35
>        Installing translation 1.35
>        Fetching activejob 7.0.4.2
>        Installing activejob 7.0.4.2
>        Fetching activerecord 7.0.4.2
>        Installing activerecord 7.0.4.2
>        Fetching activemodel-serializers-xml 1.0.2
>        Installing activemodel-serializers-xml 1.0.2
>        Fetching aws-sdk-s3 1.119.0
>        Installing aws-sdk-s3 1.119.0
>        Fetching azure-storage-common 2.0.4
>        Installing azure-storage-common 2.0.4
>        Fetching googleauth 1.3.0
>        Installing googleauth 1.3.0
>        Fetching google-cloud-core 1.6.0
>        Installing google-cloud-core 1.6.0
>        Fetching actionview 7.0.4.2
>        Installing actionview 7.0.4.2
>        Fetching dry-schema 1.13.0
>        Installing dry-schema 1.13.0
>        Fetching azure-storage-blob 2.0.3
>        Installing azure-storage-blob 2.0.3
>        Fetching google-apis-core 0.10.0
>        Installing google-apis-core 0.10.0
>        Fetching actionpack 7.0.4.2
>        Installing actionpack 7.0.4.2
>        Fetching jbuilder 2.11.5
>        Installing jbuilder 2.11.5
>        Fetching dry-validation 1.10.0
>        Installing dry-validation 1.10.0
>        Fetching google-apis-iamcredentials_v1 0.16.0
>        Installing google-apis-iamcredentials_v1 0.16.0
>        Fetching google-apis-storage_v1 0.19.0
>        Installing google-apis-storage_v1 0.19.0
>        Fetching actioncable 7.0.4.2
>        Installing actioncable 7.0.4.2
>        Fetching activestorage 7.0.4.2
>        Installing activestorage 7.0.4.2
>        Fetching actionmailer 7.0.4.2
>        Installing actionmailer 7.0.4.2
>        Fetching active_model_serializers 0.10.13
>        Installing active_model_serializers 0.10.13
>        Fetching apipie-rails 0.9.1
>        Installing apipie-rails 0.9.1
>        Fetching railties 7.0.4.2
>        Installing railties 7.0.4.2
>        Fetching sprockets-rails 3.4.2
>        Installing sprockets-rails 3.4.2
>        Fetching route_translator 13.1.0
>        Installing route_translator 13.1.0
>        Fetching config 4.1.0
>        Installing config 4.1.0
>        Fetching actionmailbox 7.0.4.2
>        Installing actionmailbox 7.0.4.2
>        Fetching actiontext 7.0.4.2
>        Installing actiontext 7.0.4.2
>        Fetching mail_form 1.9.0
>        Installing mail_form 1.9.0
>        Fetching responders 3.0.1
>        Installing responders 3.0.1
>        Fetching importmap-rails 1.1.5
>        Installing importmap-rails 1.1.5
>        Fetching lograge 0.12.0
>        Installing lograge 0.12.0
>        Fetching stimulus-rails 1.2.1
>        Installing stimulus-rails 1.2.1
>        Fetching turbo-rails 1.3.2
>        Installing turbo-rails 1.3.2
>        Fetching rails 7.0.4.2
>        Installing rails 7.0.4.2
>        Fetching devise 4.8.1
>        Installing devise 4.8.1
>        Using simple_token_authentication 1.18.0 from https://github.com/pglombardo/simple_token_authentication.git (at rails7-support@47db393)
>        Fetching google-cloud-storage 1.44.0
>        Installing google-cloud-storage 1.44.0
>        Fetching sassc-rails 2.1.2
>        Installing sassc-rails 2.1.2
>        Fetching bootstrap 5.2.3
>        Fetching sass-rails 6.0.0
>        Installing sass-rails 6.0.0
>        Installing bootstrap 5.2.3
>        Bundle complete! 50 Gemfile dependencies, 158 gems now installed.
>        Gems in the groups 'development', 'test' and 'private' were not installed.
>        Bundled gems are installed into `./vendor/bundle`
>        Post-install message from config:
>        
>        Thanks for installing Config
>        Please consider donating to our open collective to help us maintain this project.
>        
>        
>        Donate: https://opencollective.com/rubyconfig/donate
>        Bundle completed (118.27s)
>        Cleaning up the bundler cache.
> -----> Installing node-v16.18.1-linux-x64
> -----> Detecting rake tasks
> -----> Preparing app for Rails asset pipeline
>        Running: rake assets:precompile
>        rake aborted!
>        **LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.**
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.25/lib/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:3:in `<main>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:268:in `resolve_pool_config'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_handling.rb:52:in `establish_connection'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/railtie.rb:268:in `block (2 levels) in <class:Railtie>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:59:in `each'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:59:in `on_load'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/railtie.rb:262:in `block in <class:Railtie>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `instance_exec'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `run'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:60:in `run_initializers'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application.rb:372:in `initialize!'
>        /tmp/build_1abba264/config/environment.rb:5:in `<main>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application.rb:348:in `require_environment!'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application.rb:511:in `block in run_tasks_blocks'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
>        
>        **Caused by:**
>        **Gem::LoadError: pg is not part of the bundle. Add it to your Gemfile.**
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.25/lib/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:3:in `<main>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:268:in `resolve_pool_config'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/connection_handling.rb:52:in `establish_connection'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/railtie.rb:268:in `block (2 levels) in <class:Railtie>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:59:in `each'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:59:in `on_load'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/railtie.rb:262:in `block in <class:Railtie>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `instance_exec'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `run'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:60:in `run_initializers'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application.rb:372:in `initialize!'
>        /tmp/build_1abba264/config/environment.rb:5:in `<main>'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application.rb:348:in `require_environment!'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application.rb:511:in `block in run_tasks_blocks'
>        /tmp/build_1abba264/vendor/bundle/ruby/3.0.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
>        Tasks: TOP => environment
>        (See full trace by running task with --trace)
>  !
>  !     Precompiling assets failed.
>  !
>  !     Push rejected, failed to compile Ruby app.
>  !     Push failed

I have been unable to update since Mid-November, and would like to try out some of the features you have added to the repo, just can't in Heroku apparently.

**Comment by pglombardo** [comment]
Apologies for the ongoing Heroku issues @bprobst-msis.  I can't even test Heroku now because they require a credit card for the paid dynos.

There was a recent change to the app where you have to run `bundle config set with 'postgres'` (other values are `sqlite` or `mysql`) before `bundle install`.  You can see this in the [postgres Dockerfile](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/pwpush-postgres/Dockerfile#L30).

I think for heroku there is no app.json setting for this but instead you have [to add an environment variable](https://devcenter.heroku.com/articles/bundler-configuration) `BUNDLE_WITH=postgres`.

I hope this helps.  Heroku is going to be challenging to support going forward but I'll do my best for as long as I can.

**Comment by bprobst-msis** [comment]
Thank You for providing the `BUNDLE_WITH=postgres` environment variable, that allowed me to update my current instance with no issues (except one of my own making on one of the pages, silly apostrophe had to be escaped).

At least now I can complete a build again!

**Comment by bprobst-msis** [comment]
I was just able to confirm forcing the stack to heroku-20 and setting bundle_with=postgres in the `app.json` file allowed a new dyno to be deployed (at least it should work until that stack is retired).

``` 
[...]
"scripts": {
    "postdeploy": "bundle exec rake db:migrate"
  },
  "stack": "heroku-20",
  "env": {
    "BUNDLE_WITH": "postgres",
    "BUNDLE_WITHOUT": "development:test:private",
    [...]
```

**Comment by pglombardo** [comment]
> ! The Ruby version you are trying to install does not exist on this stack.
> !
> ! You are trying to install ruby-3.0.4 on heroku-22.
> !
> ! Ruby ruby-3.0.4 is present on the following stacks:
> !
> ! - heroku-18
> ! - heroku-20

If you set the environment variable `CUSTOM_RUBY_VERSION=3.2.0` and set the stack to "heroku-22" it should work.

From [this doc](https://devcenter.heroku.com/articles/ruby-support#ruby-versions):

> If your Gemfile does not contain a ruby entry, you will get MRI 3.1.2.
> 
> Default rubies are locked into the app until you specify a Ruby version. For example, if your app is using a default Ruby version of 3.0.3, you will continue to stay on 3.0.3.
> 
> We highly recommend specifying a Ruby version in your Gemfile and not relying on the default Ruby version.

The Password Pusher Gemfile [contains](https://github.com/pglombardo/PasswordPusher/blob/master/Gemfile#L3) `ruby ENV['CUSTOM_RUBY_VERSION'] || '>=2.7.0'`.  We can't call out a single Ruby version due the large number of pwpush users running in various environments.

But I believe if you set `CUSTOM_RUBY_VERSION` it should get around this issue.

Could you give that a try and let me know?

**Comment by bprobst-msis** [comment]
From what I have been able to determine so far, the `Gemfile.lock` file version will always "win" any version declarations, which is why it is trying to utilize ruby 3.0.4 as defined in that file.

I have still not found a way around this.

**Comment by pglombardo** [comment]
> From what I have been able to determine so far, the Gemfile.lock file version will always "win" any version declarations, which is why it is trying to utilize ruby 3.0.4 as defined in that file.

But doesn't the buildpack run `bundle install` anyways?  It should rewrite that Gemfile.lock I would think.

When I ran on Heroku, I was able to set a config var `CUSTOM_RUBY_VERSION=3.1.2` and it used the right Ruby.  This was more than a year ago though...

**Comment by pglombardo** [comment]
Being that so much time has passed I'll close out this issue.  If anyone still wants Heroku support, file a feature request and I'll revisit.  Thanks for reporting @bprobst-msis and apologies we couldn't get this to work!
