### ISSUE TITLE
Error in `bundle exec rake assets:precompile` in 1.23.5

### ISSUE THREAD

**Issue by mzch** [pglombardo/PasswordPusher#645]
## 🐛 Bug Report

When `RAILS_ENV=production bundle exec rake assets:precompile`, the following error happens.
```
pwpush@ll:~/PasswordPusher$ RAILS_ENV=production bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
Uglifier::Error: Unexpected token: keyword (extends)
--
  1 import { Controller } from "@hotwired/stimulus"
  2 
 => export default class extends Controller {
  4     static targets = [
  5         "payloadDiv",
  6      ]
  7 
  8     static values = {
  9         langCopied: String,
 10      }
 11 
==
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/compressing.rb:84:in `block in js_compressor='
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:59:in `block in load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:43:in `load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `block in load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/map.rb:203:in `block in fetch_or_store'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/map.rb:182:in `fetch'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/map.rb:202:in `fetch_or_store'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/bundle.rb:32:in `block in call'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/3.0.0/set.rb:344:in `each_key'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/3.0.0/set.rb:344:in `each'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/bundle.rb:31:in `call'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:59:in `block in load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:43:in `load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `block in load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/map.rb:203:in `block in fetch_or_store'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/map.rb:182:in `fetch'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/map.rb:202:in `fetch_or_store'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `load'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/base.rb:81:in `find_asset'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/base.rb:88:in `find_all_linked_assets'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/manifest.rb:125:in `each'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/manifest.rb:125:in `to_a'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/sprockets-4.2.0/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/srv/pwpush/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
Tasks: TOP => assets:precompile
```

## 🔬 How To Reproduce

1.  `git pull`
2. `bundle install`
3. `yarn install`
4. `RAILS_ENV=production bundle exec rake assets:precompie`

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [x] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?
`1.23.5`

## 📈 Expected behavior

Finish successfully.

## 📎 Additional context

Updated `config/environments/production.rb` as below:
```diff
--- config/environments/production.rb.bak       2022-12-28 06:38:09.453142571 +0900
+++ config/environments/production.rb   2023-01-11 00:13:01.039763260 +0900
@@ -30,7 +30,7 @@
   end
 
   config.assets.css_compressor = :sass
-  config.assets.js_compressor = :uglifier
+  config.assets.js_compressor = Uglifier.new(harmony: true)
 
   # Do not fallback to assets pipeline if a precompiled asset is missed.
   config.assets.compile = false
```
But the same result.

**Comment by pglombardo** [comment]
Hrm that's odd.  This code was just merged.  Give me a bit.  I'll see if I can reproduce in a clean environment.

**Comment by mzch** [comment]
Great! 👍

**Comment by pglombardo** [comment]
The fix has been merged.  If you do a `git pull --rebase` the precompile step should work now.

[Release 1.23.6](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.23.6) is building now.

Thanks for pointing this out!

**Comment by mzch** [comment]
Thanks @pglombardo ! :)
