### ISSUE TITLE
PostgreSQL passfile no longer working

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#719]
## 🔬 How To Reproduce

1. Have existing PasswordPusher setup with PostgreSQL using a `passfile` as described in #412 and https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/README.md#better-security-with-password-files and attempt to run with latest PasswordPusher Docker image.

Example:
`DATABASE_URL=postgresql://pwpush@postgres:5432/pwpush?passfile=/etc/pwpush/.db-secret`

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [x] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?
`docker.io/pglombardo/pwpush-postgres:latest`

### Screenshots
```
pwpush     | Password Pusher: migrating database to latest...
pwpush     | rake aborted!
pwpush     | ActiveRecord::ConnectionNotEstablished: fe_sendauth: no password supplied
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in new_client'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_handling.rb:280:in `connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
pwpush     | /usr/local/bundle/bin/bundle:25:in `load'
pwpush     | /usr/local/bundle/bin/bundle:25:in `<main>'
pwpush     |
pwpush     | Caused by:
pwpush     | PG::ConnectionBad: fe_sendauth: no password supplied
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/pg-1.4.5/lib/pg/connection.rb:632:in `async_connect_or_reset'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/pg-1.4.5/lib/pg/connection.rb:760:in `connect_to_hosts'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/pg-1.4.5/lib/pg/connection.rb:695:in `new'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/pg-1.4.5/lib/pg.rb:69:in `connect'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/connection_handling.rb:280:in `connection'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.1/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
pwpush     | /opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
pwpush     | /usr/local/bundle/bin/bundle:25:in `load'
pwpush     | /usr/local/bundle/bin/bundle:25:in `<main>'
pwpush     | Tasks: TOP => db:migrate
pwpush     | (See full trace by running task with --trace)
```

## 📈 Expected behavior

Database migration to perform without errors

**Comment by sirux88** [comment]
I'm not quite sure and will test tomorrow but it seems this has to do with #713 and #561.
Reason maybe that the newly introduced docker run user `pwpusher `does not have sufficent read priveledges for you're named directory `/etc/pwpush/.db-secret`

**Comment by Viajaz** [comment]
@sirux88 perm change of `o+r` for `/etc/pwpush/.db-secret` didn't make any difference it seems.

**Comment by sirux88** [comment]
@Viajaz you are right permissions don't seem to be the problem.

Are you using docker-compose? If so could you provide your docker-compose.yml
Could you aswell provide the contents of you .db-secret file? is so, please don't forget to wipe out all sensitive data

**Comment by pglombardo** [comment]
Thanks to both of you for investigating this.  I'm a bit tied up with work.

From the [postgresql docs](https://www.postgresql.org/docs/current/libpq-pgpass.html):

> On Unix systems, the permissions on a password file must disallow any access to world or group; achieve this by a command such as chmod 0600 ~/.pgpass. If the permissions are less strict than this, the file will be ignored.

So the passfile should be owned by the `pwpusher` user (uid 1000) and have mode of 0600.

Can do an `ls -lh` of the pass file and confirm the above?

I would think the ownership change is the likely culprit.

**Comment by Viajaz** [comment]
That solved that problem but it still seems to be ignoring the username in `DATABASE_URL`?
```
pwpush-db  | 2023-01-24 23:58:14.389 UTC [34] FATAL:  password authentication failed for user "passwordpusher_user"
pwpush-db  | 2023-01-24 23:58:14.389 UTC [34] DETAIL:  Role "passwordpusher_user" does not exist.
pwpush-db  |    Connection matched pg_hba.conf line 95: "host all all all md5"
pwpush     | rake aborted!
pwpush     | ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: passwordpusher_user.
pwpush     |
pwpush     | Please check your database configuration to ensure the username/password are valid.
```
I guess I could always change it DB side but still an issue none the less.

**Comment by Viajaz** [comment]
That was it, I should have knew that too I was only just reading that part of the docs recently.
All other remaining problems were related to our environment.
Thank you.
