### ISSUE TITLE
Completed 500 Internal Server Error

### ISSUE THREAD

**Issue by gsizap** [pglombardo/PasswordPusher#72]
Hi everyone,

Could you help me...  after press "push it!" the error message is displayed.

Webpage
**We're sorry, but something went wrong.**
We've been notified about this issue and we'll take a look at it shortly.

Terminal output
```
12:12:30 internalweb.1 | Processing by PasswordsController#create as HTML
12:12:30 internalweb.1 |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZtNUdLLeD4XgnZ+pkl/ehPY5Nx8JXcQdy9IZBtLRqG4fAXxCU4RuoqgLD5vJ2Mjww2lPGAJn8oDOzeSzjWBMHw==", "password"=>"[FILTERED]", "commit"=>"Push it!"}
12:12:30 internalweb.1 |    (0.2ms)  begin transaction
12:12:30 internalweb.1 |   SQL (0.4ms)  INSERT INTO "passwords" ("expire_after_days", "expire_after_views", "deletable_by_viewer", "url_token", "first_view", "payload", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["expire_after_days", 1], ["expire_after_views", 1], ["deletable_by_viewer", "t"], ["url_token", "m1cvna0odqodl7n3"], ["first_view", "t"], ["payload", "7vc2R7lKzLdqoZyu4EGgQQ==\n"], ["created_at", "2018-01-09 14:12:30.947856"], ["updated_at", "2018-01-09 14:12:30.947856"]]
12:12:30 internalweb.1 |    (0.1ms)  rollback transaction
12:12:30 internalweb.1 | Completed 500 Internal Server Error in 25ms (ActiveRecord: 2.0ms)
12:12:30 internalweb.1 | 
12:12:30 internalweb.1 | ActiveRecord::StatementInvalid (SQLite3::ReadOnlyException: attempt to write a readonly database: INSERT INTO "passwords" ("expire_after_days", "expire_after_views", "deletable_by_viewer", "url_token", "first_view", "payload", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?)):
12:12:30 internalweb.1 |   app/controllers/passwords_controller.rb:89:in `block in create'
12:12:30 internalweb.1 |   app/controllers/passwords_controller.rb:88:in `create'
```

Ps: it was working perfectly.

Thank you

**Comment by pglombardo** [comment]
> (SQLite3::ReadOnlyException: attempt to write a readonly database

Hi @gsizap,

Make sure the user account that PasswordPusher is running under has write access to the sqlite3 database file.  This file is usually in the the db directory for example `db/private.sqlite3`.

**Comment by gsizap** [comment]
It worked.  Thank you very much!

**Comment by pglombardo** [comment]
(👍≖‿‿≖)👍 👍(≖‿‿≖👍)
